import { echoes } from "./echo-data";
import { weapons } from "./weapon-data";
import { Character, CharacterConstants } from "./types";

export const charStatData: Record<string, CharacterConstants> = {
  camellya: {
    id: "camellya",
    name: "Camellya",
    weaponType: "Sword",
    weapon: "Red Spring (5☆)",
    echo: "Nightmare: Crownless",
    baseHp: 826,
    baseAtk: 36,
    baseDef: 95,
    MinorForte1: "Attack",
    MinorForte2: "Crit Dmg",
    image: "https://i.imgur.com/CpnmtcA.png",
    element: "Havoc",
    maxForte: 100,
    maxForte2: 0,
  },
  encore: {
    id: "encore",
    name: "Encore",
    weaponType: "Rectifier",
    weapon: "Stringmaster (5☆)",
    echo: "Inferno Rider",
    baseHp: 841,
    baseAtk: 34,
    baseDef: 102,
    MinorForte1: "Attack",
    MinorForte2: "Fusion",
    image: "https://i.imgur.com/KUz0Psh.png",
    element: "Fusion",
    maxForte: 100,
    maxForte2: 0,
  },
  sanhua: {
    id: "sanhua",
    name: "Sanhua",
    weaponType: "Sword",
    weapon: "Emerald of Genesis (5☆)",
    echo: "Impermanence Heron",
    baseHp: 805,
    baseAtk: 22,
    baseDef: 77,
    MinorForte1: "Attack",
    MinorForte2: "Glacio",
    image: "https://i.imgur.com/jpoAsFp.png",
    element: "Glacio",
    maxForte: 100,
    maxForte2: 0,
  },
  shorekeeper: {
    id: "shorekeeper",
    name: "Shorekeeper",
    weaponType: "Rectifier",
    weapon: "Stellar Symphony (5☆)",
    echo: "Fallacy of No Return",
    baseHp: 1337,
    baseAtk: 23,
    baseDef: 90,
    MinorForte1: "Health",
    MinorForte2: "Healing",
    image: "https://i.imgur.com/iaR9PpA.png",
    element: "Spectro",
    maxForte: 5,
    maxForte2: 0,
  },
};
