import { echoes } from "./echo-data";
import { weapons } from "./weapon-data";
import { Character, CharacterConstants } from "./types";

export const charStatData: Record<string, CharacterConstants> = {
  none: {
    name: "none",
    weapon: "",
    baseHp: 100,
    baseAtk: 10,
    baseDef: 100,
    MinorForte1: "",
    MinorForte2: "",
    image: "https://i.imgur.com/ymvvOeh.png",
    element: "",
    maxForte: 100,
    maxForte2: 0,
  },
  encore: {
    name: "Encore",
    weapon: "Rectifier",
    baseHp: 841,
    baseAtk: 34,
    baseDef: 102,
    MinorForte1: "Attack",
    MinorForte2: "Fusion",
    image: "https://i.imgur.com/KUz0Psh.png",
    element: "Fusion",
    maxForte: 100,
    maxForte2: 0,
  },
  sanhua: {
    name: "Sanhua",
    weapon: "Sword",
    baseHp: 805,
    baseAtk: 22,
    baseDef: 77,
    MinorForte1: "Attack",
    MinorForte2: "Glacio",
    image: "https://i.imgur.com/jpoAsFp.png",
    element: "Glacio",
    maxForte: 100,
    maxForte2: 0,
  },
  shorekeeper: {
    name: "Shorekeeper",
    weapon: "Rectifier",
    baseHp: 1337,
    baseAtk: 23,
    baseDef: 90,
    MinorForte1: "Health",
    MinorForte2: "Healing",
    image: "https://i.imgur.com/iaR9PpA.png",
    element: "Spectro",
    maxForte: 5,
    maxForte2: 0,
  },
  camellya: {
    name: "Camellya",
    weapon: "Sword",
    baseHp: 826,
    baseAtk: 36,
    baseDef: 95,
    MinorForte1: "Attack",
    MinorForte2: "Crit Dmg",
    image: "https://i.imgur.com/CpnmtcA.png",
    element: "Havoc",
    maxForte: 100,
    maxForte2: 0,
  },
};

export const camellya: Character = {
  name: "Camellya",
  sequenceChain: 0,
  weapon: weapons.find((weapon) => weapon.name.includes("Red Spring"))!,
  echo: echoes.find((echo) => echo.name.includes("Nightmare: Crownless"))!,
  build: "43311 Ele/Ele",
  element: "Havoc",
  maxForte: 100,
  maxForte2: 0,
  attack: 36,
  defense: 95,
  health: 826,
  crit: 5 + 40.5 + 24.3,
  critDmg: 150 + 80.5 + 16 + 44,
};

export const sanhua: Character = {
  name: "Sanhua",
  sequenceChain: 0,
  weapon: weapons.find((weapon) => weapon.name.includes("Emerald of Genesis"))!,
  echo: echoes.find((echo) => echo.name.includes("Impermanence Heron"))!,
  build: "43311 Ele/Ele",
  element: "Glacio",
  maxForte: 100,
  maxForte2: 0,
  attack: 22,
  defense: 77,
  health: 805,
  crit: 5 + 40.5 + 24.3,
  critDmg: 150 + 80.5 + 44,
};

export const shorekeeper: Character = {
  name: "Shorekeeper",
  sequenceChain: 0,
  weapon: weapons.find((weapon) => weapon.name.includes("Stellar Symphony"))!,
  echo: echoes.find((echo) => echo.name.includes("Fallacy of No Return"))!,
  build: "43311 Ele/ER",
  element: "Spectro",
  maxForte: 5,
  maxForte2: 0,
  attack: 23,
  defense: 90,
  health: 1337,
  crit: 5,
  critDmg: 150 + 80.5,
};
