import { frameToSecond } from "@/lib/utils";

export const characters: string[] = [
  "Encore",
  "Camellya",
  "Sanhua",
  "Shorekeeper",
];

export const Skills: Skill[] = [
  {
    id: "crimson_blossom",
    name: "Crimson Blossom",
    source: "Camellya",
    type: "Skill",
    hits: 2,
    hitframes: [9, 35],
    castTime: frameToSecond(85 / 60),
    cooldown: 4,
    forte: 21,
    resonance: 3.18,
    concerto: 7,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
  {
    id: "floral_ravage",
    name: "Floral Ravage",
    source: "Camellya",
    type: "Skill",
    hits: 5,
    hitframes: [17, 24, 30, 37, 74],
    castTime: frameToSecond(100 / 60),
    cooldown: 4,
    forte: 24.7,
    resonance: 3.7,
    concerto: 7,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
  {
    id: "fervor_efflorescent",
    name: "Fervor Efflorescent",
    source: "Camellya",
    type: "Liberation",
    hits: 1,
    hitframes: [1],
    castTime: frameToSecond(8 / 60),
    cooldown: 25,
    forte: 0,
    resonance: 0,
    concerto: 20,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
  {
    id: "vining_waltz_123H4",
    name: "Vining Waltz 123H4",
    source: "Camellya",
    type: "Basic",
    hits: 31,
    hitframes: [
      20, 30, 50, 62, 68, 74, 80, 86, 92, 92, 56, 62, 68, 74, 80, 86, 92, 98,
      106, 110, 116, 122, 128, 134, 140, 146, 152, 158, 180, 186, 218,
    ],

    castTime: frameToSecond(339 / 60),
    cooldown: 0,
    forte: 23.55,
    resonance: 11.79,
    concerto: 23.55,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
  {
    id: "eternal_frost",
    name: "Eternal Frost",
    source: "Sanhua",
    type: "Skill",
    hits: 1,
    hitframes: [10],
    castTime: frameToSecond(60 / 60),
    cooldown: 10,
    forte: 0,
    resonance: 10,
    concerto: 15,
    state: { isInAir: false, isGroundedForSwap: true },
    bgColor: "bg-blue-300",
    textColor: "text-gray-900",
  },
  {
    id: "glacial_gaze",
    name: "Glacial Gaze",
    source: "Sanhua",
    type: "Liberation",
    hits: 1,
    hitframes: [1],
    castTime: frameToSecond(98 / 60),
    cooldown: 16,
    forte: 0,
    resonance: -100,
    concerto: 20,
    state: { isInAir: false, isGroundedForSwap: true },
    bgColor: "bg-blue-300",
    textColor: "text-gray-900",
  },
];
