export const availableSkills: Skill[] = [
  {
    id: "fireball",
    name: "Fireball",
    description: "Launches a blazing projectile",
    castTime: 2.5,
    cooldown: 8,
    manaCost: 40,
    type: "damage",
    color: "bg-red-500",
  },
  {
    id: "heal",
    name: "Greater Heal",
    description: "Restores significant health",
    castTime: 3.0,
    cooldown: 12,
    manaCost: 60,
    type: "heal",
    color: "bg-green-500",
  },
  {
    id: "shield",
    name: "Arcane Shield",
    description: "Creates protective barrier",
    castTime: 1.5,
    cooldown: 15,
    manaCost: 35,
    type: "buff",
    color: "bg-blue-500",
  },
  {
    id: "lightning",
    name: "Lightning Bolt",
    description: "Instant electrical damage",
    castTime: 1.0,
    cooldown: 5,
    manaCost: 25,
    type: "damage",
    color: "bg-yellow-500",
  },
  {
    id: "curse",
    name: "Weakness Curse",
    description: "Reduces enemy strength",
    castTime: 2.0,
    cooldown: 20,
    manaCost: 30,
    type: "debuff",
    color: "bg-purple-500",
  },
  {
    id: "teleport",
    name: "Blink",
    description: "Instant movement ability",
    castTime: 0.5,
    cooldown: 10,
    manaCost: 20,
    type: "buff",
    color: "bg-cyan-500",
  },
  {
    id: "meteor",
    name: "Meteor Strike",
    description: "Devastating area attack",
    castTime: 4.0,
    cooldown: 30,
    manaCost: 80,
    type: "damage",
    color: "bg-orange-500",
  },
  {
    id: "regeneration",
    name: "Regeneration",
    description: "Healing over time effect",
    castTime: 1.8,
    cooldown: 25,
    manaCost: 45,
    type: "heal",
    color: "bg-emerald-500",
  },
];
