import { Echo } from "./types";

export const echoes: Record<string, Echo> = {
  "Nightmare: Crownless": {
    name: "Nightmare: Crownless",
    set: "Havoc Eclipse",
    damage: 2.646,
    castTime: 1,
    classifications: "EcHa",
    hitframes: [10],
    cooldown: 12,
    resonance: 3.67,
    charges: 3,
    hasBuff: true,
  },
  "Impermanence Heron": {
    name: "Impermanence Heron",
    set: "Moonlit Clouds",
    damage: 3.1056,
    castTime: 1.5,
    classifications: "EcHa",
    hitframes: [100],
    cooldown: 20,
    resonance: 4.85,
    charges: 0,
    hasBuff: true,
  },
  "Fallacy of No Return": {
    name: "Fallacy of No Return",
    set: "Rejuvenating Glow",
    damage: 0.1982,
    castTime: 0.01,
    classifications: "EcSpHp",
    hitframes: [45],
    cooldown: 20,
    resonance: 3.04,
    charges: 0,
    hasBuff: true,
  },
};
