import { frameToSecond } from "@/lib/utils";
import { Skill } from "./types";

export const camellya_skills: Skill[] = [
  {
    id: "crimson_blossom",
    name: "Crimson Blossom",
    damage: 1.143,
    scaling: "Attack",
    type: "Skill",
    source: "camellya",
    hitframes: [9, 35],
    castTime: frameToSecond(85),
    cooldown: 4,
    forte: 21,
    resonance: 3.18,
    concerto: 7,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
  {
    id: "floral_ravage",
    name: "Floral Ravage",
    damage: 1.323,
    scaling: "Attack",
    type: "Skill",
    source: "camellya",
    hitframes: [17, 24, 30, 37, 74],
    castTime: frameToSecond(100),
    cooldown: 4,
    forte: 24.7,
    resonance: 3.7,
    concerto: 7,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
  {
    id: "fervor_efflorescent",
    name: "Fervor Efflorescent",
    damage: 6.05,
    scaling: "Attack",
    type: "Liberation",
    source: "camellya",
    hitframes: [1],
    castTime: frameToSecond(8),
    cooldown: 25,
    forte: 0,
    resonance: 0,
    concerto: 20,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
  {
    id: "vining_waltz_123H4",
    name: "Vining Waltz 123H4",
    damage: 4.7235,
    scaling: "Attack",
    type: "Basic",
    source: "camellya",
    hitframes: [
      20, 30, 50, 62, 68, 74, 80, 86, 92, 92, 56, 62, 68, 74, 80, 86, 92, 98,
      106, 110, 116, 122, 128, 134, 140, 146, 152, 158, 180, 186, 218,
    ],
    castTime: frameToSecond(339),
    cooldown: 0,
    forte: 23.55,
    resonance: 11.79,
    concerto: 23.55,
    state: { isInAir: true, isGroundedForSwap: true },
    bgColor: "bg-pink-800",
    textColor: "text-white",
  },
];

export const sanhua_skills: Skill[] = [
  {
    id: "eternal_frost",
    name: "Eternal Frost",
    damage: 1.81,
    scaling: "Attack",
    type: "Skill",
    source: "sanhua",
    hitframes: [10],
    castTime: frameToSecond(60),
    cooldown: 10,
    forte: 0,
    resonance: 10,
    concerto: 15,
    state: { isInAir: false, isGroundedForSwap: true },
    bgColor: "bg-blue-300",
    textColor: "text-gray-900",
  },
  {
    id: "glacial_gaze",
    name: "Glacial Gaze",
    damage: 4.0716,
    scaling: "Attack",
    type: "Liberation",
    source: "sanhua",
    hitframes: [0],
    castTime: frameToSecond(98),
    cooldown: 16,
    forte: 0,
    resonance: -100,
    concerto: 20,
    state: { isInAir: false, isGroundedForSwap: true },
    bgColor: "bg-blue-300",
    textColor: "text-gray-900",
  },
];

export const shorekeeper_skills: Skill[] = [
  {
    id: "chaos_theory",
    name: "Chaos Theory",
    damage: 0.7875,
    scaling: "Attack",
    type: "Skill",
    source: "shorekeeper",
    hitframes: [1, 2, 3, 4, 5],
    castTime: frameToSecond(42),
    cooldown: 16,
    forte: 0,
    resonance: 10,
    concerto: 30,
    state: { isInAir: false, isGroundedForSwap: true },
    bgColor: "bg-yellow-200",
    textColor: "text-gray-900",
  },
  {
    id: "end_loop",
    name: "End Loop",
    damage: 0,
    scaling: "Health",
    type: "Liberation",
    source: "shorekeeper",
    hitframes: [],
    castTime: frameToSecond(3),
    cooldown: 25,
    forte: 0,
    resonance: -175,
    concerto: 20,
    state: { isInAir: false, isGroundedForSwap: true },
    bgColor: "bg-yellow-200",
    textColor: "text-gray-900",
  },
  {
    id: "origin_calculus_1234",
    name: "Origin Calculus 1234",
    damage: 1.1176,
    scaling: "Attack",
    type: "Basic",
    source: "shorekeeper",
    hitframes: [1, 2, 3, 4, 5, 6, 7],
    castTime: frameToSecond(152),
    cooldown: 0,
    forte: 5,
    resonance: 3.52,
    concerto: 11.2,
    state: { isInAir: false, isGroundedForSwap: true },
    bgColor: "bg-yellow-200",
    textColor: "text-gray-900",
  },
];
