export const weapons: Weapon[] = [
  {
    name: "Stringmaster (5☆)",
    type: "Rectifier",
    rank: 1,
    attack: 40,
    mainStat: "Crit",
    mainStatAmount: 0.08,
    buff: "Electric Amplification",
  },
  {
    name: "Stellar Symphony (5☆)",
    type: "Rectifier",
    rank: 1,
    attack: 33,
    mainStat: "Energy Regen",
    mainStatAmount: 0.1712,
    buff: "Astral Envolvement",
  },
  {
    name: "Blazing Brilliance (5☆)",
    type: "Sword",
    rank: 1,
    attack: 47,
    mainStat: "Crit Dmg",
    mainStatAmount: 0.108,
    buff: "Crimson Phoenix",
  },
  {
    name: "Red Spring (5☆)",
    type: "Sword",
    rank: 1,
    attack: 47,
    mainStat: "Crit",
    mainStatAmount: 0.054,
    buff: "Beyond the Cycle",
  },
  {
    name: "Emerald of Genesis (5☆)",
    type: "Sword",
    rank: 1,
    attack: 47,
    mainStat: "Crit",
    mainStatAmount: 0.054,
    buff: "Emerald of Genesis",
  },
];
